In [7]:
?print

In [9]:
!dir

lesson1.ipynb


In [15]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [17]:
!dir

lesson1.ipynb  script.py


In [ ]:
# %load script.py
print('hello world')


In [20]:
%run script.py

hello world


In [22]:
%pycat script.py

In [24]:
%%time
for i in range (100000):
    pass 

CPU times: user 6.37 ms, sys: 199 µs, total: 6.57 ms
Wall time: 9.78 ms


### Многомерные массивы Numpy

In [2]:
import numpy as np 

In [30]:
a = [i for i in range(10)]

In [31]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
b = np.array(a)

In [33]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b = np.array([0,1,2,3,4,5,6,7,8,9])

In [35]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b = np.array([i for i in range(10)])

In [37]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
c = (0,1,2,3,4,5,6,7,8,9)

In [39]:
b = np.array(c)

In [40]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
type(b)

numpy.ndarray

In [42]:
b = np.array(a, dtype = float)

In [43]:
a = [0,1,2,3,4,5,6,7,8,9.9]

In [44]:
b = np.array(a,dtype = int)

In [45]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b = np.array(a,dtype = float)

In [47]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [48]:
b = np.array(a,dtype = str)

In [49]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [50]:
b.dtype

dtype('<U3')

In [51]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [52]:
b[0]

'0'

In [53]:
b[1]

'1'

In [54]:
b[9]

'9.9'

In [55]:
b.ndim

1

In [56]:
b.shape

(10,)

### 2d  array 

In [64]:
b = np.array ([[0,1,2,3,4,5,6,7,8,9],
              [10,11,12,13,14,15,16,17,18,19],
              [20,21,22,23,24,25,26,27,28,29]])

In [66]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
b.shape

(3, 10)

In [68]:
b.size

30

In [69]:
b[0][0]

0

In [71]:
b[0,0]

0

In [73]:
b[1,-1]

19

In [75]:
b[0:2,0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [77]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [78]:
c = b[1:,5:]

In [79]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [80]:
c[1,4] = 999

In [81]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [82]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [88]:
c = b[1:,5:].copy()

In [90]:
c[0,0]= 777

In [91]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [92]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

### Data types 

In [93]:
b = np.array ([1.,2.,3.],dtype =np.float32)

In [94]:
b

array([1., 2., 3.], dtype=float32)

In [95]:
b = np.array ([1.,2.,3.],dtype =np.float64)

In [96]:
b

array([1., 2., 3.])

In [97]:
b.dtype

dtype('float64')

In [98]:
b = np.array ([1,2,3],dtype =np.int32)

In [99]:
b

array([1, 2, 3], dtype=int32)

In [100]:
b.dtype

dtype('int32')

In [101]:
b = np.array ([1,2,3],dtype =np.int64)

In [102]:
b

array([1, 2, 3])

In [103]:
b.dtype

dtype('int64')

### Применения библиотеки numpy для линейной алгебры  1ч

### Операции с векторами 

In [132]:
a = np.array([0,1,2,3,4])

In [133]:
b = np.array([5,6,7,8,9])

In [112]:
a.size

5

In [113]:
b.size

5

In [116]:
a.shape


(5,)

In [115]:
b.shape

(5,)

### Сложение векторов 

In [134]:
c = a + b 

In [135]:
c

array([ 5,  7,  9, 11, 13])

In [119]:
x1 = [0,1,2,3,4]
x2 = [5,6,7,8,9]

In [120]:
x1 + x2 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [136]:
c = np.add(a,b)

In [122]:
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [139]:
a = np.array([5,4,8,4,3])
b = np.array([3,5,7,1,3])

In [130]:
d = a -b 

In [131]:
d

array([ 2, -1,  1,  3,  0])

 #### Альтернативный способ

In [140]:
d = np.subtract(a,b)

In [141]:
d

array([ 2, -1,  1,  3,  0])

#### При вычитании весторов их размерность должна совподать 

In [142]:
a.shape == b.shape 

True

### Умножение на скаляр 

In [143]:
a = np.array([5,4,8,4,3])

In [144]:
c = a * 2

In [145]:
c

array([10,  8, 16,  8,  6])

In [146]:
c = -10 * a

In [147]:
c

array([-50, -40, -80, -40, -30])

In [148]:
c = 0.5 * a 

In [149]:
c

array([2.5, 2. , 4. , 2. , 1.5])

##### Сравним с умножением натурального числа на список 

In [150]:
2 * [0,1,2,3]

[0, 1, 2, 3, 0, 1, 2, 3]

##### Альтернативные способы убножения на скаляр

In [151]:
a = np.array([5,4,8,4,3])
a

array([5, 4, 8, 4, 3])

In [153]:
#Вариант1\метод
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [154]:
#Вариант2\функция
np.dot(-10,a)

array([-50, -40, -80, -40, -30])

In [155]:
#Вариант3
np.multiply(-10,a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов 

In [162]:
a = np.array([1,2,3])
b = np.array([4,5,6])


array([4, 5, 6])

In [157]:
a.shape

(3,)

In [158]:
b.shape

(3,)

In [167]:
sp = (a[0] * b[0]) + (a[1] * b[1]) +  (a[2] * b[2])
sp

32

In [168]:
a @ b

32

In [171]:
sp = np.dot(a,b)
sp

32

### Опирации с матрицами

In [172]:
A = np.array([[0,1],
              [2,3],
              [4,5]])

In [173]:
B = np.array([[6,7],
              [8,9],
              [10,11]])

In [174]:
A.shape

(3, 2)

In [175]:
B.shape

(3, 2)

#### Сложение матриц

In [176]:
C = A + B 

In [177]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [178]:
C = np.add (A,B)

In [179]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Вычитание матриц 

In [184]:
D = A - C

In [185]:
D

array([[ -6,  -7],
       [ -8,  -9],
       [-10, -11]])

In [189]:
D = np.subtract(C,B)

In [190]:
D

array([[0, 1],
       [2, 3],
       [4, 5]])

#### Умножений матрицы на скаляр 

In [192]:
X = np.array([[1,2],[3,4]])

In [193]:
Y = X * 3

In [194]:
Y

array([[ 3,  6],
       [ 9, 12]])

In [195]:
Y = np.dot(X,3)

In [196]:
Y

array([[ 3,  6],
       [ 9, 12]])

### Умножение матриц 

In [3]:
x1 = np.array([[1,2],
               [3,4],
               [5,6]])

In [4]:
x2 = np.array([[7,8,9,10],
               [11,12,13,14]])

In [9]:
x1[1],x2[0]

(array([3, 4]), array([ 7,  8,  9, 10]))

In [10]:
x1.shape, x2.shape

((3, 2), (2, 4))

In [11]:
z = np.dot(x1,x2)

In [12]:
z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

#### Как получен нулевой элемент

In [13]:
z [0,0]

29

In [14]:
x1[0,0]*x2[0,0]+x1[0,1]*x2[1,0]

29

In [15]:
z[0,1]

32

In [16]:
x1[0,0] *x2[0,1]+ x1[0,1] * x2[1,1]

32

#### Модуль numpy.linag: возведение в квадрат

In [17]:
A = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

In [18]:
A_sqere = np.dot(A,A)

In [19]:
A_sqere

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [21]:
A_sqere = np.linalg.matrix_power(A,2)

In [22]:
A_sqere

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

#### Единичная матрица

###### Единичная матрица - квадратная матрица с единицами по главной диаганали и нулямями в остальных

In [24]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Умножение матрицу на единичную матрицу

In [26]:
A = np.array([[1,2],
              [3,4],
              [5,6]])

#### Случай 1 

In [28]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [29]:
np.dot(A,I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [31]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.dot(I,A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### Транспонирование матрицы

In [33]:
A = np.array([[11,13],
              [16,9],
              [8,15]])

In [35]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

In [36]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

In [38]:
X = np.array([[1,2],
              [3,4],
              [5,6]])

In [39]:
Y = np.array([[0,1],
              [3,4],
              [6,7],
              [2,5]])

In [40]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [41]:
 np.dot(X,Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

#### Вычесление и определения ранга матрицы 

### Пример1

In [42]:
A = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

In [43]:
np.linalg.det(A)

0.0

In [44]:
np.linalg.matrix_rank(A)

2

In [45]:
B = np.array([[7,4,5],
              [8,3,2],
              [6,10,12]])

In [47]:
np.linalg.det(B)

85.99999999999997

In [48]:
np.linalg.matrix_rank(B)

3

#### Пример 3. Можно узнать ранг матрицы не не определитель так как она не квадратнавя

In [49]:
С = np.array([[1,2],
              [3,4],
              [5,6,]])

In [50]:
np.linalg.matrix_rank(С)

2

#### Вычисление обратной матрицы 

In [51]:
B = np.array([[7,4,5],
              [8,3,2],
              [6,10,12]])

In [52]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [53]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

### Автомотическое создание массивов 

In [56]:
a = np.zeros ((3,4))

In [57]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [65]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [67]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [68]:
np.linspace(0,9.9,100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

#### numpy.logspace - обе границы включены, но это не сами числа а степени  числа 10

In [69]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

#### Генерация случайных чисел 

In [71]:
np.random.sample()

0.5390100419175001

In [72]:
np.random.sample(3)

array([0.96096423, 0.24409358, 0.8939712 ])

In [74]:
np.random.sample((2,3))

array([[0.27297487, 0.50660252, 0.08008753],
       [0.55504755, 0.13987672, 0.91475973]])

#### Трехмерный массив 

In [75]:
np.random.sample((48,64,3))

array([[[0.04701035, 0.10420778, 0.37689969],
        [0.62513802, 0.82730403, 0.99036375],
        [0.5903873 , 0.9878627 , 0.8428863 ],
        ...,
        [0.50550394, 0.8451067 , 0.09100186],
        [0.69918666, 0.9413303 , 0.63867031],
        [0.66988687, 0.07166929, 0.42171438]],

       [[0.9378609 , 0.93168746, 0.90359917],
        [0.13746581, 0.82554858, 0.5601145 ],
        [0.76668401, 0.600347  , 0.79883865],
        ...,
        [0.27136006, 0.71741893, 0.11729036],
        [0.97558065, 0.70388696, 0.0701804 ],
        [0.56430599, 0.82518572, 0.29199741]],

       [[0.97077733, 0.95135776, 0.90546227],
        [0.98121401, 0.05827444, 0.34049841],
        [0.38417431, 0.02650001, 0.12020668],
        ...,
        [0.64914416, 0.79295677, 0.15591068],
        [0.9018438 , 0.10018424, 0.01752763],
        [0.39088963, 0.63373126, 0.36810941]],

       ...,

       [[0.55467385, 0.60496481, 0.37477444],
        [0.09231251, 0.85435135, 0.66169661],
        [0.47240226, 0

#### numpy.random.randn - случайные числа с нормальным 
#### распределением (Среднее значение - 0, среднеквадратичное отклонение =1) 

In [77]:
np.random.randn(10)

array([ 2.47678275,  1.22185384, -0.24888031,  0.73740963,  0.25542279,
       -0.38915216, -0.8514923 ,  2.20870808, -0.23719004,  1.31411051])

In [78]:
np.random.randn(3,4)

array([[-0.46414666,  0.5486584 , -1.11401145, -0.66029077],
       [-0.71208345, -0.54542545, -0.84641632, -0.78875242],
       [ 0.28866569,  1.14754251,  0.23373221, -0.36125699]])

#### numpy.random.randint - массив из целых чисел

In [80]:
np.random.randint(0,100,10)

array([76, 42, 18, 20, 32,  2, 70, 73, 54, 87])

In [81]:
 np.random.randint(0,10,(3,4))

array([[8, 1, 7, 8],
       [1, 8, 0, 9],
       [7, 6, 8, 1]])

#### numpy.random.choice -- случайный выбор элемента из массива 

In [82]:
b = np.random.randint(0,10,8)
b

array([2, 9, 5, 9, 3, 8, 0, 2])

In [85]:
np.random.choice(b)

5

In [86]:
np.random.choice(b,6)

array([8, 9, 2, 0, 2, 2])

#### numpy.random.seed - инициализация гениратора случайных чисел (Будут генерироваться одни и теже числа если указать сид

In [113]:
np.random.seed(42)

In [117]:
np.random.randint(0,10,3)

array([4, 3, 7])

#### Изменения формы массива 

In [122]:
a = np.arange(12)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
## Вычислит сам количество столбцов 
np.reshape (a,(3,-1)) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
#inplace
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

In [126]:
a = np.zeros((2,3))

In [127]:
b = np.ones((2,3))

#### Соединение строк (вертикально)

In [129]:
v = np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [130]:
np.concatenate((a,b),axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Соединение строк (горизонтально)

In [133]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [134]:
np.concatenate((a,b),axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

#### Соединить в глубину.

In [135]:
d = np.dstack([a,b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

### Выбор данных

In [137]:
a = np.random.randint(0,20,10)
a 

array([ 2,  1, 11,  5,  1,  0, 11, 11, 16,  9])

In [138]:
a[a > 10]

array([11, 11, 11, 16])

In [141]:
a[(a>10)&(a % 2 == 0)]

array([16])

In [142]:
a [(a > 10) | (a % 3 == 0 ) ]

array([11,  0, 11, 11, 16,  9])

#### numpy.where - первый вариант применения

In [143]:
a

array([ 2,  1, 11,  5,  1,  0, 11, 11, 16,  9])

In [144]:
# Возврощает индексы чисел, удовлетворяющие условию.
np.where (a>10)

(array([2, 6, 7, 8]),)

In [145]:
a[np.where(a>10)]

array([11, 11, 11, 16])

#### Второй вариант 

In [146]:
a = [1,4,7]
b = [9,2,5]

In [147]:
# Если в условии True, то берем елемент из масива а,
# усли false то из b
np.where([True,False,True],a,b)

array([1, 2, 7])

### Сортировка 

In [191]:
a = np.array([[0, 1, 2, 6],
              [6, 4, 5, 7],
              [3, 7, 8, 3]])

In [150]:
a[[2,1,0],:]

array([[6, 7, 8, 3],
       [3, 4, 5, 7],
       [0, 1, 2, 6]])

In [181]:
a[[0,1,2],:1]

array([[0],
       [3],
       [6]])

In [186]:
a.argsort(axis = 0)

array([[0, 0, 0, 2],
       [1, 1, 1, 0],
       [2, 2, 2, 1]])

In [187]:
a[:,0].argsort()

array([0, 1, 2])

In [193]:
a[a[:,0].argsort(),:]

array([[0, 1, 2, 6],
       [3, 7, 8, 3],
       [6, 4, 5, 7]])

#### Случайное перемешивание массивов 

одномерные массивы 

In [194]:
a = np.arange(10)

In [195]:
np.random.shuffle(a)

In [196]:
a

array([1, 8, 7, 5, 4, 9, 0, 3, 6, 2])

Двумерные массивы 

In [197]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [200]:
#inplace
np.random.shuffle(a)
a

array([[ 6,  7,  8],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [ 0,  1,  2]])

#### Математические действия с массивами 

Применение математических действий ко всему массиву 

In [203]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [205]:
# Логорифм по основание е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [206]:
# Експонента 
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [208]:
a.sum()

21

In [209]:
a.sum(axis = 0)

array([5, 7, 9])

In [210]:
a.sum(axis = 1)

array([ 6, 15])

In [211]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
a + 10 

array([[11, 12, 13],
       [14, 15, 16]])

#### Поэлементное (не матричное) Умножение 

In [213]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [214]:
b = np.arange(12,24).reshape(-1,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [215]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting (на примере сложения)

In [216]:
a = np.array([[2,5],
              [3,4],
              [6,1]])

###### 1 случай. совподает только число столбцов

In [217]:
b  = np.array([1,2])

In [218]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

#### 2 случай - совподает только число строк 

In [219]:
c = np.array([[1],
              [2],
              [3]])

In [220]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции 

In [222]:
a = np.random.randint(0,12,(3,4))
a

array([[ 1,  9,  8,  9],
       [ 4,  1,  3, 11],
       [11,  6, 11,  7]])

In [225]:
a.min(axis = 0)

array([1, 1, 3, 7])

In [226]:
a.max(axis = 1)

array([ 9, 11, 11])

In [227]:
# Среднее значение 
a.mean (axis = 0)

array([5.33333333, 5.33333333, 7.33333333, 9.        ])

In [228]:
#Среднее квадратичное 
a.std(axis = 0)

array([4.18993503, 3.29983165, 3.29983165, 1.63299316])

### Запись и чтение массива из файла 

In [229]:
np.save('a.npy',a)

In [230]:
b = np.load('a.npy')

In [231]:
b

array([[ 1,  9,  8,  9],
       [ 4,  1,  3, 11],
       [11,  6, 11,  7]])

# Pandas 

In [1]:
import pandas as pd 
import numpy as np 

In [5]:
a = [2,5,7,8,3]

In [7]:
b = pd.Series(a)

In [8]:
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

In [10]:
b = pd.Series(a, index = ['a','b','c','d','e'])
b

a    2
b    5
c    7
d    8
e    3
dtype: int64

In [12]:
from datetime import date 

In [13]:
ind =  [date(y,m,d) for y,m,d in [(2018,1,15),(2018,4,22),(2018,12,8),(2016,2,1),(2012,4,17)]]

In [14]:
b = pd.Series(a, index = ind)

In [15]:
b

2018-01-15    2
2018-04-22    5
2018-12-08    7
2016-02-01    8
2012-04-17    3
dtype: int64

In [16]:
b. index

Index([2018-01-15, 2018-04-22, 2018-12-08, 2016-02-01, 2012-04-17], dtype='object')

In [17]:
b.index[0].year

2018

In [18]:
b.index[2].day

8

In [19]:
b.index[4].month

4

In [21]:
# придаем к виду дататайм
b.index = pd.to_datetime(b.index, format = '%Y-%m-%d')

In [22]:
b.index.year

Int64Index([2018, 2018, 2018, 2016, 2012], dtype='int64')

In [23]:
# тоже самое без беблиотеки datatime
b.index.day[2]

8

In [27]:
# Индексы могут быть не уникальными 
b = pd.Series(a, index = [0,4,2,6,7])
b

0    2
4    5
2    7
6    8
7    3
dtype: int64

0    2
4    5
2    7
6    8
7    3
dtype: int64

In [29]:
#Можно менять индекс 
b.index = [10,11,13,14,15]
b

10    2
11    5
13    7
14    8
15    3
dtype: int64

In [32]:
# Тип данных 
b = pd.Series(a, dtype = np.int64)
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

In [34]:
#Изменить 
b = b.astype(np.float64)
b

0    2.0
1    5.0
2    7.0
3    8.0
4    3.0
dtype: float64

In [38]:
# Создать Series из словаря 
d = {'1st':'a', '2st':'b', '3st':'c', '4st':'d', '5st':'e'}

In [40]:
b = pd.Series(d)
b

1st    a
2st    b
3st    c
4st    d
5st    e
dtype: object

#### Просмотр данных 

In [41]:
b = pd.Series([5,2,6,2,5,4,3])

In [42]:
# Просмотр индексов

In [43]:
b.index

RangeIndex(start=0, stop=7, step=1)

In [44]:
# Посмотреть данные в виде массива Numpy (ndarray)
b.values

array([5, 2, 6, 2, 5, 4, 3])

In [45]:
b

0    5
1    2
2    6
3    2
4    5
5    4
6    3
dtype: int64

In [46]:
b[3]

2

In [48]:
b[[0,1,2]]

0    5
1    2
2    6
dtype: int64

In [50]:
#Посмотреть первые несколько элементов
b.head(4)

0    5
1    2
2    6
3    2
dtype: int64

In [52]:
b.tail(3)

4    5
5    4
6    3
dtype: int64

#### Условия 

In [54]:
b[b>2]

0    5
2    6
4    5
5    4
6    3
dtype: int64

In [56]:
# Либо 
b[(b == 7)| (b % 3 == 0 )]

2    6
6    3
dtype: int64

In [57]:
# Изменение элементов
b[0] =  2
b

0    2
1    2
2    6
3    2
4    5
5    4
6    3
dtype: int64

In [59]:
b[b<5] = 0
b

0    0
1    0
2    6
3    0
4    5
5    0
6    0
dtype: int64

In [61]:
b[[0,1,2]] =1 
b

0    1
1    1
2    1
3    0
4    5
5    0
6    0
dtype: int64

### Добовление данных 

In [63]:
b = b.append(pd.Series({6:10,7:15,8:11,9:131}))
b

0      1
1      1
2      1
3      0
4      5
5      0
6      0
6     10
7     15
8     11
9    131
dtype: int64

In [64]:
b = b.drop([0,1,2])
b

3      0
4      5
5      0
6      0
6     10
7     15
8     11
9    131
dtype: int64

### Запись и чтение в фаил. 

In [65]:
b.to_pickle('b.pk1')

In [66]:
b2 = pd.read_pickle('b.pk1')

In [67]:
b2

3      0
4      5
5      0
6      0
6     10
7     15
8     11
9    131
dtype: int64

### DataFrame
двумерная структура данных беблиотеки Pandas 

In [72]:
df = pd.DataFrame({'Col1': ['a','b','c','d','e','f','g','h'],
                   'Col2':[1,6,3,8,5,2,7,5]}, columns =['Col1','Col2'])

In [73]:
df

Col1  Col2
0    a     1
1    b     6
2    c     3
3    d     8
4    e     5
5    f     2
6    g     7
7    h     5

### Просмотр информации о DataFreame 

In [74]:
df.shape

(8, 2)

In [76]:
df.columns

Index(['Col1', 'Col2'], dtype='object')

In [77]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Col1    8 non-null      object
 1   Col2    8 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes


In [81]:
df.describe()

Col2
count  8.000000
mean   4.625000
std    2.445842
min    1.000000
25%    2.750000
50%    5.000000
75%    6.250000
max    8.000000

In [83]:
df.head()

Col1  Col2
0    a     1
1    b     6
2    c     3
3    d     8
4    e     5

In [84]:
df['Col1'].head()

0    a
1    b
2    c
3    d
4    e
Name: Col1, dtype: object

In [85]:
df.Col1.head()

0    a
1    b
2    c
3    d
4    e
Name: Col1, dtype: object

In [86]:
#Изменение индекса
df.index = [2,3,4,12,7,5,11,14]
df

Col1  Col2
2     a     1
3     b     6
4     c     3
12    d     8
7     e     5
5     f     2
11    g     7
14    h     5

In [87]:
# Выбор данных по индексу
df.loc[2,'Col1']

'a'

In [89]:
df.loc[2,:]

Col1    a
Col2    1
Name: 2, dtype: object

In [94]:
df.loc[2:11,:]

Col1  Col2
2     a     1
3     b     6
4     c     3
12    d     8
7     e     5
5     f     2
11    g     7

#### Выбор данных по опзиции 

In [95]:
df.iloc[0,:]

Col1    a
Col2    1
Name: 2, dtype: object

In [96]:
df.iloc[2:4,:]

Col1  Col2
4     c     3
12    d     8

In [97]:
df.iloc[2:4,0]

4     c
12    d
Name: Col1, dtype: object

### Выбор по условию 

In [98]:
df.loc[df['Col1'] == 'b', :]

Col1  Col2
3    b     6

In [101]:
df.loc[df['Col1'] == 'b', 'Col2']

3    6
Name: Col2, dtype: int64

In [102]:
df.loc[df['Col1'] == 'b', :].values

array([['b', 6]], dtype=object)

In [104]:
df.loc[df['Col2'] > 4, 'Col1']

3     b
12    d
7     e
11    g
14    h
Name: Col1, dtype: object

In [115]:
#Логическое "И"
df.loc[(df['Col2'] > 4) & (df['Col1'] != 'g'), :]

Col1  Col2
3     b     6
12    d     8
7     e     5
14    h     5

In [118]:
# Логическое "ИЛИ"
df.loc[(df['Col2'] > 4) | (df['Col2'] % 9 == 0), :]

Col1  Col2
3     b     6
12    d     8
7     e     5
11    g     7
14    h     5

In [125]:
# Задать отрезак 
df.loc[df['Col2'].between(6,7), :]

Col1  Col2
3     b     6
11    g     7

In [128]:
# Указать элементы которые нас интересуют 
df.loc[df['Col1'].isin(['a','b','c']), :]

Col1  Col2
2    a     1
3    b     6
4    c     3

In [129]:
# Задать отрицание для обратного результата 
df.loc[~df['Col1'].isin(['a','b','c']), :]

Col1  Col2
12    d     8
7     e     5
5     f     2
11    g     7
14    h     5

#### Метод Query


In [131]:
df

Col1  Col2
2     a     1
3     b     6
4     c     3
12    d     8
7     e     5
5     f     2
11    g     7
14    h     5

In [132]:
df.query('Col1 == "b"')

Col1  Col2
3    b     6

In [140]:
df.query('Col2 > 4')

Col1  Col2
3     b     6
12    d     8
7     e     5
11    g     7
14    h     5

In [142]:
#Столбец Data Frame в виде Series
s = df['Col1']

In [143]:
s

2     a
3     b
4     c
12    d
7     e
5     f
11    g
14    h
Name: Col1, dtype: object

In [144]:
type(s)

pandas.core.series.Series

### Получение DataFrame из Series

In [145]:
df2 = pd.DataFrame(s)
df2

Col1
2     a
3     b
4     c
12    d
7     e
5     f
11    g
14    h

#Копирование DataFrame
df_copy = df.copy()
df_copy

### Случайный выбор n-го количества строк

In [147]:
df.sample(n=2)

Col1  Col2
14    h     5
12    d     8

#### Случайный выбор доли от исходного датафрейма

In [149]:
df.sample(frac = 0.5)

Col1  Col2
12    d     8
14    h     5
3     b     6
5     f     2

In [151]:
# Случайный выбор с возврощением (строки могут повторяться)
df.sample(frac = 0.5, replace = True)

Col1  Col2
7     e     5
3     b     6
14    h     5
7     e     5

In [153]:
# random_state - для воспроизводимости перемешивания
df.sample(frac = 1.0 , random_state = 42)

Col1  Col2
3     b     6
5     f     2
2     a     1
14    h     5
4     c     3
7     e     5
12    d     8
11    g     7

### Запись и чтение DataFrame в csv

In [154]:
df.to_csv('Test.csv', sep = ';', index = False)

In [155]:
df_new = pd.read_csv('Test.csv', sep = ';')

In [156]:
df_new

Col1  Col2
0    a     1
1    b     6
2    c     3
3    d     8
4    e     5
5    f     2
6    g     7
7    h     5

#### Запись в exel  и pickle с помощью to_exel, to_pickle. 
#### Чтение - read_exel, read_pickle

## Слияние Данных 

In [160]:
authors = pd.DataFrame({'author_id':[1,2,3], 'author_name': ['Pushkin','Tolstoy','Dostoevsky']},
                       columns = ['author_id','author_name'])

In [161]:
authors

author_id author_name
0          1     Pushkin
1          2     Tolstoy
2          3  Dostoevsky

In [162]:
books = pd.DataFrame({'author_id':[2,3,3,4], 'book_title': ['War and Pice','The idiot','Crime and Punisment',
                                                            'Fathers and Sons']})

In [163]:
books

author_id           book_title
0          2         War and Pice
1          3            The idiot
2          3  Crime and Punisment
3          4     Fathers and Sons

## Merge

In [164]:
df1 = pd.merge(authors,books, on ='author_id', how = 'inner')
df1

author_id author_name           book_title
0          2     Tolstoy         War and Pice
1          3  Dostoevsky            The idiot
2          3  Dostoevsky  Crime and Punisment

### Left merge

In [166]:
df2 = pd.merge(authors,books, on ='author_id', how = 'left')
df2

author_id author_name           book_title
0          1     Pushkin                  NaN
1          2     Tolstoy         War and Pice
2          3  Dostoevsky            The idiot
3          3  Dostoevsky  Crime and Punisment

## Right

In [167]:
df3 = pd.merge(authors,books, on ='author_id', how = 'right')
df3

author_id author_name           book_title
0          2     Tolstoy         War and Pice
1          3  Dostoevsky            The idiot
2          3  Dostoevsky  Crime and Punisment
3          4         NaN     Fathers and Sons

## Outer 

In [169]:
df4 = pd.merge(authors,books, on ='author_id', how = 'outer')
df4

author_id author_name           book_title
0          1     Pushkin                  NaN
1          2     Tolstoy         War and Pice
2          3  Dostoevsky            The idiot
3          3  Dostoevsky  Crime and Punisment
4          4         NaN     Fathers and Sons

#### Работа с пропущенными данными 

In [171]:
df4.loc[df4['book_title'].isnull(),:]

author_id author_name book_title
0          1     Pushkin        NaN

In [172]:
df4.loc[df4['book_title'].notnull(),:]

author_id author_name           book_title
1          2     Tolstoy         War and Pice
2          3  Dostoevsky            The idiot
3          3  Dostoevsky  Crime and Punisment
4          4         NaN     Fathers and Sons

In [179]:
df4['book_title'] = df4['book_title'].fillna('unknown')

In [180]:
df4['author_name'].fillna('unknown', inplace = True)
df4

author_id author_name           book_title
0          1     Pushkin               unknow
1          2     Tolstoy         War and Pice
2          3  Dostoevsky            The idiot
3          3  Dostoevsky  Crime and Punisment
4          4      unknow     Fathers and Sons

### Добовляем столбцы в Data_ Frame 

In [184]:
df4.loc[(df4['author_name'] != 'unknow') & (df4['book_title'] != 'unknow'), 'quantity'] = 1

In [185]:
df4

author_id author_name           book_title  quantity
0          1     Pushkin               unknow       NaN
1          2     Tolstoy         War and Pice       1.0
2          3  Dostoevsky            The idiot       1.0
3          3  Dostoevsky  Crime and Punisment       1.0
4          4      unknow     Fathers and Sons       NaN

In [186]:
df4['quantity'].fillna(0, inplace = True)

In [187]:
df4

author_id author_name           book_title  quantity
0          1     Pushkin               unknow       0.0
1          2     Tolstoy         War and Pice       1.0
2          3  Dostoevsky            The idiot       1.0
3          3  Dostoevsky  Crime and Punisment       1.0
4          4      unknow     Fathers and Sons       0.0

In [188]:
#Поменяем тип данных на инт 
df4['quantity'] = df4['quantity'].astype(int)
df4

author_id author_name           book_title  quantity
0          1     Pushkin               unknow         0
1          2     Tolstoy         War and Pice         1
2          3  Dostoevsky            The idiot         1
3          3  Dostoevsky  Crime and Punisment         1
4          4      unknow     Fathers and Sons         0

In [198]:
# сделаем полноценным индексом
df4.set_index('author_id', inplace = True)
df4

index author_name           book_title  quantity
author_id                                                  
1            0.0     Pushkin               unknow         0
3            2.0  Dostoevsky            The idiot         1
3            3.0  Dostoevsky  Crime and Punisment         1
4            4.0      unknow     Fathers and Sons         0
2            NaN     Tolstoy        War and Peace         1

In [191]:
# Обратно
df4.reset_index(inplace = True)
df4

index  author_id author_name           book_title  quantity
0      0          1     Pushkin               unknow         0
1      1          2     Tolstoy         War and Pice         1
2      2          3  Dostoevsky            The idiot         1
3      3          3  Dostoevsky  Crime and Punisment         1
4      4          4      unknow     Fathers and Sons         0

### Удаление

In [192]:
df4['price'] = 500
df4

index  author_id author_name           book_title  quantity  price
0      0          1     Pushkin               unknow         0    500
1      1          2     Tolstoy         War and Pice         1    500
2      2          3  Dostoevsky            The idiot         1    500
3      3          3  Dostoevsky  Crime and Punisment         1    500
4      4          4      unknow     Fathers and Sons         0    500

In [193]:
#Удалить столбец
df4 = df4.drop('price', axis = 1)
df4 

index  author_id author_name           book_title  quantity
0      0          1     Pushkin               unknow         0
1      1          2     Tolstoy         War and Pice         1
2      2          3  Dostoevsky            The idiot         1
3      3          3  Dostoevsky  Crime and Punisment         1
4      4          4      unknow     Fathers and Sons         0

In [203]:
# Строку по значению индекса
df4 = df4.drop(4, axis = 0)

### Сортировка 

In [204]:
# Вернем удаленную строку
df4 = df4.append(pd.DataFrame({'author_id': [2],
                               'author_name' : ['Tolstoy'],
                               'book_title': ['War and Peace'],
                               'quantity': [1]},
                               columns = ['author_id', 'author_name', 'book_title', 'quantity']),
                            ignore_index = True)
df4

index author_name           book_title  quantity  author_id
0    0.0     Pushkin               unknow         0        NaN
1    2.0  Dostoevsky            The idiot         1        NaN
2    3.0  Dostoevsky  Crime and Punisment         1        NaN
3    4.0      unknow     Fathers and Sons         0        NaN
4    NaN     Tolstoy        War and Peace         1        2.0

отсортируем по столбцу author_id

In [205]:
df4 = df4.sort_values(by='author_id')
df4

index author_name           book_title  quantity  author_id
4    NaN     Tolstoy        War and Peace         1        2.0
0    0.0     Pushkin               unknow         0        NaN
1    2.0  Dostoevsky            The idiot         1        NaN
2    3.0  Dostoevsky  Crime and Punisment         1        NaN
3    4.0      unknow     Fathers and Sons         0        NaN

Переустановим индекс

In [208]:
df4 = df4.reset_index(drop = True)
df4

index author_name           book_title  quantity  author_id
0    NaN     Tolstoy        War and Peace         1        2.0
1    0.0     Pushkin               unknow         0        NaN
2    2.0  Dostoevsky            The idiot         1        NaN
3    3.0  Dostoevsky  Crime and Punisment         1        NaN
4    4.0      unknow     Fathers and Sons         0        NaN

### Соединение DataFreme 

Конкатинация по оси 0 (добовление новых строк)

In [209]:
df5 = pd.DataFrame({'author_id': [3,5], 'author_name': ['Dostovsky','Chehov'],
                   'book_title' : ['The Gambler', 'Three Sisters'],
                   'quantity': [2,3]},
                  columns= ['author_id','author_name', 'book_title', 'quantity'])
df5

author_id author_name     book_title  quantity
0          3   Dostovsky    The Gambler         2
1          5      Chehov  Three Sisters         3

In [210]:
df6 = pd.concat([df4,df5], axis = 0, ignore_index=True)
df6

index author_name           book_title  quantity  author_id
0    NaN     Tolstoy        War and Peace         1        2.0
1    0.0     Pushkin               unknow         0        NaN
2    2.0  Dostoevsky            The idiot         1        NaN
3    3.0  Dostoevsky  Crime and Punisment         1        NaN
4    4.0      unknow     Fathers and Sons         0        NaN
5    NaN   Dostovsky          The Gambler         2        3.0
6    NaN      Chehov        Three Sisters         3        5.0

Конкатенация по оси 1 ( добовление новых столбцов)

In [211]:
prices = pd.DataFrame({'price': [700,450,500,400,350]}, columns = ['price'], index = [1,2,3,5,6])
prices

price
1    700
2    450
3    500
5    400
6    350

In [212]:
df7 = pd.concat([df6,prices], axis = 1)
df7

index author_name           book_title  quantity  author_id  price
0    NaN     Tolstoy        War and Peace         1        2.0    NaN
1    0.0     Pushkin               unknow         0        NaN  700.0
2    2.0  Dostoevsky            The idiot         1        NaN  450.0
3    3.0  Dostoevsky  Crime and Punisment         1        NaN  500.0
4    4.0      unknow     Fathers and Sons         0        NaN    NaN
5    NaN   Dostovsky          The Gambler         2        3.0  400.0
6    NaN      Chehov        Three Sisters         3        5.0  350.0

## Применение функций и методов

In [213]:
df7['total'] = df7['quantity'] * df7['price']
df7

index author_name           book_title  quantity  author_id  price   total
0    NaN     Tolstoy        War and Peace         1        2.0    NaN     NaN
1    0.0     Pushkin               unknow         0        NaN  700.0     0.0
2    2.0  Dostoevsky            The idiot         1        NaN  450.0   450.0
3    3.0  Dostoevsky  Crime and Punisment         1        NaN  500.0   500.0
4    4.0      unknow     Fathers and Sons         0        NaN    NaN     NaN
5    NaN   Dostovsky          The Gambler         2        3.0  400.0   800.0
6    NaN      Chehov        Three Sisters         3        5.0  350.0  1050.0

In [214]:
df7['price'].max()

700.0

In [215]:
df7['price'].min()

350.0

In [216]:
df7['price'].mean()

480.0

In [217]:
df7['price'].median()

450.0

In [218]:
df7['price'].std()

135.09256086106296

In [220]:
df7['price'].var()

18250.0

In [221]:
#Несколько максимальных значений
df7.nlargest(3,'price')

index author_name           book_title  quantity  author_id  price  total
1    0.0     Pushkin               unknow         0        NaN  700.0    0.0
3    3.0  Dostoevsky  Crime and Punisment         1        NaN  500.0  500.0
2    2.0  Dostoevsky            The idiot         1        NaN  450.0  450.0

In [223]:
df7['author_name'].unique()

array(['Tolstoy', 'Pushkin', 'Dostoevsky', 'unknow', 'Dostovsky',
       'Chehov'], dtype=object)

In [225]:
# Количество уникальных значений в столбце. 
df7['author_name'].nunique()

6

In [226]:
# Сколько раз каждое значение встречается  
df7['author_name'].value_counts()

Dostoevsky    2
Chehov        1
unknow        1
Dostovsky     1
Pushkin       1
Tolstoy       1
Name: author_name, dtype: int64

#### Построчное применение функций и методов:

In [229]:
df7['book_title'].apply(lambda x: x.upper())

0          WAR AND PEACE
1                 UNKNOW
2              THE IDIOT
3    CRIME AND PUNISMENT
4       FATHERS AND SONS
5            THE GAMBLER
6          THREE SISTERS
Name: book_title, dtype: object

### Групперовка данных

1 ый способ

In [232]:
# Найти максимальную цену на книги по каждому автору.
df7.groupby('author_name')['price'].max()

author_name
Chehov        350.0
Dostoevsky    500.0
Dostovsky     400.0
Pushkin       700.0
Tolstoy         NaN
unknow          NaN
Name: price, dtype: float64

2 ой Способ

In [235]:
price_agg = df7.groupby('author_name').agg({'price': 'max'})
price_agg

price
author_name       
Chehov       350.0
Dostoevsky   500.0
Dostovsky    400.0
Pushkin      700.0
Tolstoy        NaN
unknow         NaN

In [236]:
#Обновим индекс и переименуюем колонку.
price_agg = price_agg.reset_index()
price_agg = price_agg.rename(columns = {'price': 'max_price'})
price_agg

author_name  max_price
0      Chehov      350.0
1  Dostoevsky      500.0
2   Dostovsky      400.0
3     Pushkin      700.0
4     Tolstoy        NaN
5      unknow        NaN